---
- hosts: {{ form_host }}
  tasks:
    - name: set facts
      set_fact:
        podname: "{{ form_name }}"
        registry: "{{ form_repo }}"
        msg: "{{ form_msg }}"
        
    - name: Commit {{ podname }} 
      shell: podman commit -f docker -m '"'{{ msg }}'"' {{ podname }} {{ registry }}
      
    - name: Push to {{ registry }}
      shell: podman push {{ registry }} #--tls-verify=false
