---
- hosts: all
  tasks:
      - name: set fact1
        set_fact:
          flag1: "{{ ' ' if form_name == '' else '--name ' }}"
      - debug:
          var: flag1
      - name: set fact2
          #podname: "{{ flag1 + form_name }}"
      - debug:
          var: podname
      - name: Create The Container 
        shell: podman run -d {{ podname }} ubuntu:18.04 sleep 3000
