---
- hosts: all
  tasks:
      - name: set fact
        set_fact:
          podname: "{{ '--name 123' if form_name != ' ' else ' ' }}"
      - name: Create The Container 
        shell: podman run -d {{ podname }} ubuntu:18.04 sleep 3000
