---
- hosts: all
  tasks:
      - name: set fact
        set_fact:
          podname: "{{ ' ' if form_name == '' else '--name $(form_name)' }}"
      - name: Create The Container 
        shell: podman run -d {{ podname }} ubuntu:18.04 sleep 3000
