---
- hosts: all
  tasks:
      - name: set fact1
        set_fact:
          podnameflag: "{{ ' ' if form_name == '' else '--name ' }}"
          volume1flag: "{{ ' ' if form_volume1 == '' else '-v ' }}"
          volume2flag: "{{ ' ' if form_volume2 == '' else '-v ' }}"
      - debug:
          var: 
          - podnameflag
          - volume1flag
          - volume2flag
      - name: set fact2
        set_fact:
          podname: "{{ podnameflag + form_name }}"
          volume1name: "{{ volume1flag + form_volume1 }}"
          volume2name: "{{ volume2flag + form_volume2 }}"
      - debug:
          var: 
          - podname
          - volume1name
          - volume2name
      #- name: Create The Container 
        #shell: podman run -d {{ podname }} ubuntu:18.04 sleep 3000
